name: CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main
      - stable
      - v*

permissions: read-all

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true  # si un build échoue, les autres s’arrêtent aussi
      matrix:
        build_type: [ Release ]
        os: [ ubuntu-22.04, windows-2022 ]
        include:
          - os: ubuntu-22.04
            build_type: Debug

    name: Build on ${{ matrix.os }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true

      - name: Cache Conan
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: ${{ runner.os }}-conan-${{ matrix.build_type }}-${{ hashFiles('conanfile.py') }}
          restore-keys: |
            ${{ runner.os }}-conan-${{ matrix.build_type }}-

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Set up Clang (Linux)
        if: runner.os == 'Linux'
        env:
          LLVM_VERSION: 16
        run: |
          set -e
          sudo apt-get update -y -q
          sudo apt-get install -y -q build-essential lsb-release wget software-properties-common
          sudo wget https://apt.llvm.org/llvm.sh
          sudo chmod +x llvm.sh
          sudo ./llvm.sh ${LLVM_VERSION}
          sudo apt-get install -y -q libc++-${LLVM_VERSION}-dev libc++abi-${LLVM_VERSION}-dev
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${LLVM_VERSION} 200
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${LLVM_VERSION} 200
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Set up MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86_64

      - name: Set up CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install and Configure Conan
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install conan
          conan profile detect --force

      - name: Install Dependencies with Conan
        run: |
          set -e
          if [ "${{ runner.os }}" == "Linux" ]; then
            conan install . --build=missing -s compiler.cppstd=20 -s build_type=${{ matrix.build_type }} -c tools.cmake.cmaketoolchain:generator=Ninja -s compiler.libcxx=libc++
          else
            conan install . --build=missing -s compiler.cppstd=20 -s build_type=${{ matrix.build_type }} -c tools.cmake.cmaketoolchain:generator=Ninja
          fi

      - name: Configure and Build with CMake
        run: |
          set -e
          cmake -S . -B build/${{ matrix.build_type }} -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build build/${{ matrix.build_type }}

      - name: Run Tests
        run: |
          set -e
          ctest --test-dir build/${{ matrix.build_type }}
